# Generated by Django 3.2.9 on 2021-11-09 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='mediafiles')),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('info', models.TextField()),
                ('fee', models.FloatField(default=1000)),
                ('duration', models.CharField(help_text='like 3 months or 12 months', max_length=10)),
                ('created_date', models.DateField()),
                ('last_date', models.DateField()),
                ('total_seats', models.PositiveIntegerField(default=30)),
                ('seats_reserved', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('seats_remaining', models.PositiveIntegerField(blank=True, null=True)),
                ('is_activated', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('msg', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='teachers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='medaifiles')),
                ('name', models.CharField(max_length=20)),
                ('profession', models.CharField(default='Graphic Designer', max_length=20)),
                ('instagram', models.URLField(blank=True, null=True)),
                ('facebook', models.URLField(blank=True, null=True)),
                ('twitter', models.URLField(blank=True, null=True)),
                ('linkdin', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
